import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// These sidebar files are auto-generated by `npm run gen-api-docs`.
// Run `npm run regen` after updating openapi/*.yaml to regenerate them.
// eslint-disable-next-line @typescript-eslint/no-require-imports
const publicApiSidebar = require('./docs/api/public/sidebar');
// eslint-disable-next-line @typescript-eslint/no-require-imports
const privateApiSidebar = require('./docs/api/private/sidebar');

const sidebars: SidebarsConfig = {

  gettingStartedSidebar: [
    {
      type: 'doc',
      id: 'index',
      label: 'Welcome',
    },
    {
      type: 'category',
      label: '🚀 Installation',
      collapsed: false,
      items: [
        'installation/index',
        'installation/system-requirements',
        'installation/rocky-linux',
        'installation/ubuntu',
        'installation/cpanel-shared-hosting',
        'installation/azure',
        'installation/ssl-https',
      ],
    },
    {
      type: 'category',
      label: '⚙️ First Run',
      collapsed: false,
      items: [
        'getting-started/first-run',
        'getting-started/first-week',
        'getting-started/features-overview',
      ],
    },
  ],

  userGuideSidebar: [
    {
      type: 'doc',
      id: 'user-guide/index',
      label: 'User Guide Overview',
    },
    {
      type: 'category',
      label: '👥 People & Families',
      items: [
        'user-guide/persons',
        'user-guide/families',
        'user-guide/classifications',
        'user-guide/custom-fields',
        'user-guide/custom-fields-types',
        'user-guide/properties',
        'user-guide/notes',
        'user-guide/search',
      ],
    },
    {
      type: 'category',
      label: '📅 Groups & Events',
      items: [
        'user-guide/groups',
        'user-guide/events',
        'user-guide/sunday-school',
        'user-guide/volunteers',
        'user-guide/kiosk-devices',
      ],
    },
    {
      type: 'category',
      label: '💰 Finance',
      items: [
        'user-guide/finances',
        'user-guide/cart',
        'user-guide/fundraiser',
      ],
    },
    {
      type: 'category',
      label: '📧 Communications',
      items: [
        'user-guide/email',
        'user-guide/reports-and-queries',
        'user-guide/geographic',
        'user-guide/data-import',
      ],
    },
  ],

  apiSidebar: [
    {
      type: 'category',
      label: '🔓 Public API',
      collapsed: false,
      items: [
        {
          type: 'doc',
          id: 'api/public/index',
          label: 'Overview',
        },
        ...publicApiSidebar,
      ],
    },
    {
      type: 'category',
      label: '🔒 Private API',
      collapsed: false,
      items: [
        {
          type: 'doc',
          id: 'api/private/index',
          label: 'Overview',
        },
        ...privateApiSidebar,
      ],
    },
  ],

  adminSidebar: [
    {
      type: 'doc',
      id: 'administration/index',
      label: 'Administration Overview',
    },
    {
      type: 'category',
      label: '🔧 System Management',
      items: [
        'administration/users',
        'administration/security',
        'administration/secret-keys',
        'administration/email-setup',
        'administration/localization',
        'administration/reset-password',
      ],
    },
    {
      type: 'category',
      label: '⚙️ Configuration',
      items: [
        'administration/maps-and-geocoding',
        'administration/server-locale',
      ],
    },
    {
      type: 'category',
      label: '🔄 Maintenance',
      items: [
        'administration/upgrade',
        'administration/backup-restore',
        'administration/rollback',
        'administration/file-system-permissions',
      ],
    },
    {
      type: 'category',
      label: '🩺 Troubleshooting',
      items: [
        'administration/troubleshooting',
        'administration/faqs',
        'administration/error',
        'administration/logging-and-diagnostics',
        'administration/bug-reporting-and-diagnostics',
        'administration/reporting-issues',
      ],
    },
  ],

};

export default sidebars;
