import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebar: SidebarsConfig = {
  apisidebar: [
    {
      type: "doc",
      id: "api/private/churchcrm-private-api",
    },
    {
      type: "category",
      label: "Calendar",
      link: {
        type: "doc",
        id: "api/private/calendar",
      },
      items: [
        {
          type: "doc",
          id: "api/private/get-system-calendars",
          label: "List all system calendars",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/private/get-system-calendar-events",
          label: "Get events from a system calendar",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/private/get-system-calendar-event-by-id",
          label: "Get a single event from a system calendar",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/private/get-system-calendar-full-calendar-events",
          label: "Get system calendar events in FullCalendar format",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/private/get-user-calendars",
          label: "List user-created calendars",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/private/new-calendar",
          label: "Create a new calendar",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/private/get-user-calendar-by-id",
          label: "Get a specific user calendar",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/private/delete-user-calendar",
          label: "Delete a user calendar",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "api/private/get-user-calendar-full-calendar-events",
          label: "Get user calendar events in FullCalendar format",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/private/get-user-calendar-events",
          label: "Get events for a user calendar",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/private/new-calendar-access-token",
          label: "Generate a new public access token for a calendar",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/private/delete-calendar-access-token",
          label: "Remove the public access token from a calendar",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "api/private/get-events-counters",
          label: "Get today's event counters for the dashboard menu badges",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/private/get-all-events",
          label: "List all events",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/private/new-event",
          label: "Create a new event",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/private/get-event-types",
          label: "List all event types",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/private/get-event",
          label: "Get an event by ID",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/private/update-event",
          label: "Update an existing event",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/private/delete-event",
          label: "Delete an event",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "api/private/get-event-primary-contact",
          label: "Get an event's primary contact person",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/private/get-event-secondary-contact",
          label: "Get an event's secondary contact person",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/private/get-event-location",
          label: "Get an event's location",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/private/get-event-audience",
          label: "Get an event's audience (linked groups)",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/private/set-event-time",
          label: "Update an event's start and end times",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "People",
      link: {
        type: "doc",
        id: "api/private/people",
      },
      items: [
        {
          type: "doc",
          id: "api/private/get-person-photo",
          label: "Get a person's uploaded photo",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/private/upload-person-photo",
          label: "Upload a person's photo (base64)",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/private/delete-person-photo",
          label: "Delete a person's uploaded photo",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "api/private/get-person-avatar",
          label: "Get a person's avatar info (initials, gravatar)",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/private/get-person",
          label: "Get a person by ID",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/private/delete-person",
          label: "Delete a person",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "api/private/add-person-to-cart",
          label: "Add a person to the selection cart",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/private/set-person-role",
          label: "Set a person's family role",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/private/search-persons",
          label: "Search persons by name or email",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/private/get-self-registered-persons",
          label: "List recently self-registered persons",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/private/get-all-roles",
          label: "List all family roles",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/private/get-email-duplicates",
          label: "Find duplicate email addresses across persons and families",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/private/get-latest-persons",
          label: "List the 10 most recently added persons",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/private/get-updated-persons",
          label: "List the 10 most recently edited persons",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/private/get-persons-with-birthdays",
          label: "List persons with birthdays in a ±7-day window around today",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "Families",
      link: {
        type: "doc",
        id: "api/private/families",
      },
      items: [
        {
          type: "doc",
          id: "api/private/get-families-whose-all-members-are-in-the-session-cart",
          label: "Get families whose all members are in the session cart",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/private/get-families-with-no-email-address-on-record",
          label: "Get families with no email address on record",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/private/search-families-by-name-max-15-results",
          label: "Search families by name (max 15 results)",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/private/get-the-last-100-self-registered-families",
          label: "Get the last 100 self-registered families",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/private/get-the-last-100-families-with-self-verification-notes",
          label: "Get the last 100 families with self-verification notes",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/private/get-families-with-pending-unused-non-expired-self-verify-tokens",
          label: "Get families with pending (unused, non-expired) self-verify tokens",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/private/find-a-family-by-check-scan-string",
          label: "Find a family by check scan string",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/private/12-ab-7668-a-38-d-4-b-9-f-9-a-09-f-2-a-6314-fa-41-b",
          label: "Get families with wedding anniversaries within 7 days of today",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/private/78-e-3-ca-7-d-537-e-14-b-376-d-9603100-d-97-ae-1",
          label: "Get the 10 most recently added families",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/private/4-c-21568-cb-8-dd-4-b-4629-d-379-ca-1-bd-41894",
          label: "Get the 10 most recently updated families",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/private/get-uploaded-photo-for-a-family-binary-image",
          label: "Get uploaded photo for a family (binary image)",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/private/upload-a-family-photo-from-base-64-data-edit-records-role-required",
          label: "Upload a family photo from base64 data (EditRecords role required)",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/private/delete-a-familys-uploaded-photo-edit-records-role-required",
          label: "Delete a family's uploaded photo (EditRecords role required)",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "api/private/get-avatar-info-json-for-a-family-for-client-side-rendering",
          label: "Get avatar info JSON for a family (for client-side rendering)",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/private/get-a-family-object-by-id",
          label: "Get a family object by ID",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/private/get-geolocation-and-driving-distance-from-church-for-a-family",
          label: "Get geolocation and driving distance from church for a family",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/private/get-previous-and-next-family-i-ds-for-navigation",
          label: "Get previous and next family IDs for navigation",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/private/send-a-verification-email-to-the-family",
          label: "Send a verification email to the family",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/private/generate-a-new-family-self-verify-url-token",
          label: "Generate a new family self-verify URL token",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/private/mark-a-family-as-verified-immediately",
          label: "Mark a family as verified immediately",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/private/activate-or-deactivate-a-family",
          label: "Activate or deactivate a family",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "Groups",
      link: {
        type: "doc",
        id: "api/private/groups",
      },
      items: [
        {
          type: "doc",
          id: "api/private/list-all-groups",
          label: "List all groups",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/private/create-a-new-group-manage-group-role-role-required",
          label: "Create a new group (ManageGroupRole role required)",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/private/get-groups-formatted-for-calendar-display",
          label: "Get groups formatted for calendar display",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/private/get-i-ds-of-groups-whose-all-members-are-in-the-session-cart",
          label: "Get IDs of groups whose all members are in the session cart",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/private/get-a-single-group-by-id",
          label: "Get a single group by ID",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/private/update-group-name-type-and-description-manage-group-role-role-required",
          label: "Update group name, type, and description (ManageGroupRole role required)",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/private/delete-a-group-manage-group-role-role-required",
          label: "Delete a group (ManageGroupRole role required)",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "api/private/check-whether-all-members-of-a-group-are-in-the-session-cart",
          label: "Check whether all members of a group are in the session cart",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/private/get-members-of-a-group-with-family-address-info",
          label: "Get members of a group with family address info",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/private/get-group-member-role-memberships-events-roles-per-member",
          label: "Get group member-role memberships (events/roles per member)",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/private/get-the-role-options-for-a-group",
          label: "Get the role options for a group",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/private/add-a-new-role-to-a-group-manage-group-role-role-required",
          label: "Add a new role to a group (ManageGroupRole role required)",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/private/remove-a-person-from-a-group-manage-group-role-role-required",
          label: "Remove a person from a group (ManageGroupRole role required)",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "api/private/add-a-person-to-a-group-manage-group-role-role-required",
          label: "Add a person to a group (ManageGroupRole role required)",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/private/update-a-group-members-role-manage-group-role-role-required",
          label: "Update a group member's role (ManageGroupRole role required)",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/private/update-a-group-role-name-or-sort-order-manage-group-role-role-required",
          label: "Update a group role name or sort order (ManageGroupRole role required)",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/private/delete-a-group-role-manage-group-role-role-required",
          label: "Delete a group role (ManageGroupRole role required)",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "api/private/set-the-default-role-for-a-group-manage-group-role-role-required",
          label: "Set the default role for a group (ManageGroupRole role required)",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/private/enable-or-disable-group-specific-properties-manage-group-role-role-required",
          label: "Enable or disable group-specific properties (ManageGroupRole role required)",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/private/set-a-groups-active-status-manage-group-role-role-required",
          label: "Set a group's active status (ManageGroupRole role required)",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/private/set-the-email-export-flag-for-a-group-manage-group-role-role-required",
          label: "Set the email export flag for a group (ManageGroupRole role required)",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "Properties",
      link: {
        type: "doc",
        id: "api/private/properties",
      },
      items: [
        {
          type: "doc",
          id: "api/private/c-892797-ab-05-f-9-f-276-d-27-a-66-e-69893-fd-1",
          label: "Get all available person property definitions",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/private/4664-af-36-def-75-fb-0-d-3-fbdcdf-49-d-21585",
          label: "Add or update a property on a person (MenuOptions role required)",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/private/2-af-3-cf-88-d-42-ba-4-c-25-b-65401397-f-6568-c",
          label: "Remove a property from a person (MenuOptions role required)",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "api/private/2039-dca-67-fb-8-dcd-91-b-09-c-60-b-78094-b-20",
          label: "Get all available family property definitions",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/private/7-ef-25-b-63-c-1711-b-96-df-7-e-22-cd-35-c-85-d-6-f",
          label: "Get properties assigned to a specific person",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/private/8-fd-4-e-3-be-5-f-9790-c-5-e-8-e-592435-e-549840",
          label: "Get properties assigned to a specific family",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/private/b-52-f-1-f-13-fae-3920442-a-4977268-aa-2222",
          label: "Add or update a property on a family (MenuOptions role required)",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/private/290-de-930428-c-9-af-8-ddb-84089-d-075-d-2-fe",
          label: "Remove a property from a family (MenuOptions role required)",
          className: "api-method delete",
        },
      ],
    },
    {
      type: "category",
      label: "Finance",
      link: {
        type: "doc",
        id: "api/private/finance",
      },
      items: [
        {
          type: "doc",
          id: "api/private/get-all-deposits-finance-role-required",
          label: "Get all deposits (Finance role required)",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/private/create-a-new-deposit-finance-role-required",
          label: "Create a new deposit (Finance role required)",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/private/get-deposits-from-the-last-90-days-finance-role-required",
          label: "Get deposits from the last 90 days (Finance role required)",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/private/get-a-single-deposit-by-id-finance-role-required",
          label: "Get a single deposit by ID (Finance role required)",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/private/update-an-existing-deposit-finance-role-required",
          label: "Update an existing deposit (Finance role required)",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/private/delete-a-deposit-finance-role-required",
          label: "Delete a deposit (Finance role required)",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "api/private/get-ofx-export-data-for-a-deposit-finance-role-required",
          label: "Get OFX export data for a deposit (Finance role required)",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/private/generate-and-stream-a-pdf-report-for-a-deposit-finance-role-required",
          label: "Generate and stream a PDF report for a deposit (Finance role required)",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/private/download-a-csv-export-of-payments-for-a-deposit-finance-role-required",
          label: "Download a CSV export of payments for a deposit (Finance role required)",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/private/get-pledge-items-for-a-deposit-finance-role-required",
          label: "Get pledge items for a deposit (Finance role required)",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/private/get-payment-items-for-a-deposit-finance-role-required",
          label: "Get payment items for a deposit (Finance role required)",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/private/get-all-payments-finance-role-required",
          label: "Get all payments (Finance role required)",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/private/submit-a-new-pledge-or-payment-finance-role-required",
          label: "Submit a new pledge or payment (Finance role required)",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/private/get-pledge-and-payment-history-for-a-family-finance-role-required",
          label: "Get pledge and payment history for a family (Finance role required)",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/private/delete-a-payment-by-group-key-finance-role-required",
          label: "Delete a payment by group key (Finance role required)",
          className: "api-method delete",
        },
      ],
    },
    {
      type: "category",
      label: "Users",
      link: {
        type: "doc",
        id: "api/private/users",
      },
      items: [
        {
          type: "doc",
          id: "api/private/get-a-named-setting-value-for-a-user",
          label: "Get a named setting value for a user",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/private/set-a-named-setting-value-for-a-user",
          label: "Set a named setting value for a user",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/private/9-c-5-b-7-f-81-e-23978171-e-18-bfaa-621-d-3-afb",
          label: "Regenerate the API key for a user",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/private/59-e-86-f-576-bf-97599899-bf-3-a-42-c-85-d-068",
          label: "Update a named config string for a user",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "2FA",
      link: {
        type: "doc",
        id: "api/private/2-fa",
      },
      items: [
        {
          type: "doc",
          id: "api/private/4-ef-4967-f-921432-b-697-d-4-e-6-b-10-f-192-e-1-e",
          label: "Begin 2FA enrollment — provision a new TOTP secret and return a QR code data URI",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/private/3-eecff-3759-ce-549-b-52249-d-1-b-862-f-24-eb",
          label: "Generate new 2FA recovery codes for the current user",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/private/082-cadb-8-d-10369-ca-71-a-0-ab-95-de-48-ef-55",
          label: "Remove the 2FA secret from the current user (disables 2FA)",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/private/6487-c-0-abc-311-e-2-f-3-adc-531-da-5-bb-8-a-3-c-0",
          label: "Get the current user's 2FA QR code as a PNG image",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/private/a-7-d-29-c-600-e-46-bbd-933-e-54-a-003-c-030108",
          label: "Validate a TOTP enrollment code to complete 2FA setup",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/private/79-f-52733691250300717-c-3-ca-5137-c-616",
          label: "Get the 2FA enabled status for the current user",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "System",
      link: {
        type: "doc",
        id: "api/private/system",
      },
      items: [
        {
          type: "doc",
          id: "api/private/dc-27-d-4-ecd-49-d-53-f-0-f-86-cbcf-381-c-25-b-8-a",
          label: "Trigger background timer jobs (scheduled task runner)",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/private/962-bf-4374-c-22-a-8090-d-2-a-6-dd-90-efc-0-c-4-c",
          label: "Get custom person fields filtered by type ID (Admin role required)",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/private/create-a-local-database-backup-admin-role-required",
          label: "Create a local database backup (Admin role required)",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/private/trigger-a-remote-web-dav-backup-via-the-external-backup-plugin-admin-role-required",
          label: "Trigger a remote (WebDAV) backup via the External Backup plugin (Admin role required)",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/private/restore-the-database-from-a-backup-file-admin-role-required",
          label: "Restore the database from a backup file (Admin role required)",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/private/download-a-backup-file-by-name-admin-role-required",
          label: "Download a backup file by name (Admin role required)",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/private/9589-fd-11-a-6970-c-70598-c-60-b-8553-cfe-5-e",
          label: "Get internal system URL paths for debugging (Admin role required)",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/private/generate-a-git-hub-issue-body-pre-filled-with-system-diagnostics",
          label: "Generate a GitHub issue body pre-filled with system diagnostics",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/private/039-f-967-a-16-c-76-a-56-ac-2-a-2042-f-40158-be",
          label: "Get all translatable terms stored in the database (Admin role required)",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/private/d-67011-aae-959-ed-9-fd-77-c-417-c-9-bd-9-bd-09",
          label: "Get current UI notifications (update alerts, system messages)",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "Admin",
      link: {
        type: "doc",
        id: "api/private/admin",
      },
      items: [
        {
          type: "doc",
          id: "api/private/export-all-people-as-a-ch-meetings-compatible-csv-file-admin-role-required",
          label: "Export all people as a ChMeetings-compatible CSV file (Admin role required)",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/private/drop-all-database-tables-and-views-clear-uploaded-images-and-destroy-the-session-admin-role-required",
          label: "Drop all database tables and views, clear uploaded images, and destroy the session (Admin role required)",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "api/private/import-demo-data-into-the-application-admin-role-required",
          label: "Import demo data into the application (Admin role required)",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/private/get-orphaned-files",
          label: "List orphaned files",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/private/delete-all-orphaned-files",
          label: "Delete all orphaned files",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/private/download-latest-release",
          label: "Download the latest release from GitHub",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/private/do-upgrade",
          label: "Apply the system upgrade",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/private/refresh-upgrade-info",
          label: "Refresh upgrade information from GitHub",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/private/reset-a-users-password-to-a-random-value-and-email-it-to-them-admin-role-required",
          label: "Reset a user's password to a random value and email it to them (Admin role required)",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/private/disable-two-factor-authentication-for-a-user-admin-role-required",
          label: "Disable two-factor authentication for a user (Admin role required)",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/private/reset-failed-login-counter-and-send-unlock-email-admin-role-required",
          label: "Reset failed login counter and send unlock email (Admin role required)",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/private/delete-a-user-account-admin-role-required",
          label: "Delete a user account (Admin role required)",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "api/private/get-permission-flags-for-a-user-admin-role-required",
          label: "Get permission flags for a user (Admin role required)",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "Cart",
      link: {
        type: "doc",
        id: "api/private/cart",
      },
      items: [
        {
          type: "doc",
          id: "api/private/get-the-current-session-people-cart-contents",
          label: "Get the current session people cart contents",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/private/add-persons-a-family-or-a-group-to-the-session-cart",
          label: "Add persons, a family, or a group to the session cart",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/private/remove-persons-or-a-family-from-the-cart-or-empty-the-entire-cart",
          label: "Remove persons or a family from the cart, or empty the entire cart",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "api/private/move-all-persons-in-the-cart-into-a-group-with-a-specified-role",
          label: "Move all persons in the cart into a group with a specified role",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/private/remove-all-members-of-a-group-from-the-session-cart",
          label: "Remove all members of a group from the session cart",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "Search",
      link: {
        type: "doc",
        id: "api/private/search",
      },
      items: [
        {
          type: "doc",
          id: "api/private/search-persons-families-groups-deposits-payments-and-calendar-events",
          label: "Search persons, families, groups, deposits, payments, and calendar events",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "Map",
      link: {
        type: "doc",
        id: "api/private/map",
      },
      items: [
        {
          type: "doc",
          id: "api/private/2598-abc-84-c-9-af-84-ffe-13-f-20625-aa-7-bfb",
          label: "Geocode an address — returns latitude and longitude",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/private/b-18-edb-4-f-383-d-3-cf-32-ec-4-a-82-dd-84-b-5-a-9-e",
          label: "Get geocoded map items — families, group members, or cart persons",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "Kiosk",
      link: {
        type: "doc",
        id: "api/private/kiosk",
      },
      items: [
        {
          type: "doc",
          id: "api/private/get-kiosk-devices",
          label: "List all kiosk devices",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/private/allow-kiosk-registration",
          label: "Open a 30-second kiosk registration window",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/private/reload-kiosk",
          label: "Reload a kiosk device",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/private/identify-kiosk",
          label: "Trigger identification signal on a kiosk device",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/private/accept-kiosk",
          label: "Accept a pending kiosk device",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/private/set-kiosk-assignment",
          label: "Set kiosk event assignment",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/private/delete-kiosk",
          label: "Delete a kiosk device",
          className: "api-method delete",
        },
      ],
    },
    {
      type: "category",
      label: "Plugins",
      link: {
        type: "doc",
        id: "api/private/plugins",
      },
      items: [
        {
          type: "doc",
          id: "api/private/list-plugins",
          label: "List all available plugins",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/private/get-plugin",
          label: "Get plugin details",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/private/enable-plugin",
          label: "Enable a plugin",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/private/disable-plugin",
          label: "Disable a plugin",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/private/update-plugin-settings",
          label: "Update plugin settings",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/private/test-plugin-connection",
          label: "Test plugin connection with provided settings",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/private/reset-plugin-settings",
          label: "Reset all settings for a plugin",
          className: "api-method post",
        },
      ],
    },
  ],
};

export default sidebar.apisidebar;
